name: messenger
description: "A simple messenger in Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  equatable: ^2.0.5
  talker_bloc_logger: ^4.4.0
  google_fonts: ^6.2.1
  auto_route: ^9.2.0
  talker_flutter: ^4.4.0
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  formz: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^2.4.11
  auto_route_generator: 9.0.0


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/

flutter_intl:
  enabled: true
