name: messenger
description: "A simple messenger in Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  equatable: ^2.0.5
  talker_bloc_logger: ^4.3.4
  google_fonts: ^6.2.1
  auto_route: ^8.3.0
  talker_flutter: ^4.3.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route_generator: ^8.1.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
